version: '2'

services:
  app:
    image: tornadocash/tornado-root-updater
    depends_on: [redis]
    restart: always
    env_file: .env
    environment:
      REDIS_URL: redis://redis/0

  redis:
    image: redis
    restart: always
    command: [redis-server, --appendonly, 'yes']
    volumes:
      - redis:/data

volumes:
  redis:
